# Generated by Django 2.1.4 on 2023-02-08 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFABackupCodes',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mfa_backup_codes', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('_values', models.TextField(verbose_name='backup codes')),
            ],
            options={
                'verbose_name': 'MFA Backup Code',
                'verbose_name_plural': 'MFA Backup Codes',
            },
        ),
        migrations.CreateModel(
            name='MFAMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('secret', models.CharField(max_length=255, verbose_name='secret')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('code_last_generated_at', models.DateTimeField(null=True, verbose_name='code last generated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_methods', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'MFA Method',
                'verbose_name_plural': 'MFA Methods',
            },
        ),
        migrations.CreateModel(
            name='MFAUsedCode',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, verbose_name='id')),
                ('code', models.CharField(max_length=6, verbose_name='code')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='used_at')),
                ('expires_at', models.DateTimeField(verbose_name='expires_at')),
                ('method', models.CharField(max_length=255, verbose_name='method')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_used_codes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'MFA Last Used Code',
                'verbose_name_plural': 'MFA Last Used Codes',
            },
        ),
    ]
