# Generated by Django 4.1.5 on 2023-01-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trench", "0005_mfabackupcodes_mfausedcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mfamethod",
            name="code_last_generated_at",
            field=models.DateTimeField(
                null=True, verbose_name="code last generated at"
            ),
        ),
    ]
